package com.oa.mapper;

import com.oa.entity.Course;

public interface CourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    int insert(Course record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table course
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    int insertSelective(Course record);
}