package com.oa.mapper;

import com.oa.entity.Leave;

import java.util.List;

public interface LeaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    int insert(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    int insertSelective(Leave record);

    List<Leave> listPositiveLeaves();

    int updateVerifyOpinion(Leave leave);
}