package com.oa.mapper;

import com.oa.entity.Leave;

public interface LeaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    int insert(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    int insertSelective(Leave record);
}