package com.oa.mapper;

import com.oa.entity.Reimbursement;

import java.util.List;

public interface ReimbursementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reimbursement
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    int insert(Reimbursement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reimbursement
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    int insertSelective(Reimbursement record);

    List<Reimbursement> listPositiveReimbursement();

    int updateVerifyOpinion(Reimbursement reimbursement);
}