package com.oa.mapper;

import com.oa.entity.Reimbursement;

public interface ReimbursementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reimbursement
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    int insert(Reimbursement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reimbursement
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    int insertSelective(Reimbursement record);
}