package com.oa.mapper;

import com.oa.entity.Student;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    int insertSelective(Student record);

    Student selectByUserName(String username);
    String getNameFromId(int id);
}