package com.oa.mapper;

import com.oa.entity.Student;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table students
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    int insertSelective(Student record);
}