package com.oa.mapper;

import com.oa.entity.Teacher;

public interface TeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    int insert(Teacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teachers
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    int insertSelective(Teacher record);

    Teacher selectByUserName(String name);

    String getNameFromId(int id);
}