package com.oa.entity;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminId
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private Integer adminid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminName
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String adminname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminPassword
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String adminpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.sex
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.email
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.AdminInfo
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String admininfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminId
     *
     * @return the value of admin.adminId
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminId
     *
     * @param adminid the value for admin.adminId
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminName
     *
     * @return the value of admin.adminName
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getAdminname() {
        return adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminName
     *
     * @param adminname the value for admin.adminName
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setAdminname(String adminname) {
        this.adminname = adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminPassword
     *
     * @return the value of admin.adminPassword
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getAdminpassword() {
        return adminpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminPassword
     *
     * @param adminpassword the value for admin.adminPassword
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setAdminpassword(String adminpassword) {
        this.adminpassword = adminpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.sex
     *
     * @return the value of admin.sex
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.sex
     *
     * @param sex the value for admin.sex
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.email
     *
     * @return the value of admin.email
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.email
     *
     * @param email the value for admin.email
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.AdminInfo
     *
     * @return the value of admin.AdminInfo
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getAdmininfo() {
        return admininfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.AdminInfo
     *
     * @param admininfo the value for admin.AdminInfo
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setAdmininfo(String admininfo) {
        this.admininfo = admininfo;
    }
}