package com.oa.entity;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.courseKey
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String coursekey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.name
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.semester
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private Byte semester;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.hours
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private Byte hours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column course.credit
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private Byte credit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.courseKey
     *
     * @return the value of course.courseKey
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getCoursekey() {
        return coursekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.courseKey
     *
     * @param coursekey the value for course.courseKey
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setCoursekey(String coursekey) {
        this.coursekey = coursekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.name
     *
     * @return the value of course.name
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.name
     *
     * @param name the value for course.name
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.semester
     *
     * @return the value of course.semester
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public Byte getSemester() {
        return semester;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.semester
     *
     * @param semester the value for course.semester
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setSemester(Byte semester) {
        this.semester = semester;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.hours
     *
     * @return the value of course.hours
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public Byte getHours() {
        return hours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.hours
     *
     * @param hours the value for course.hours
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setHours(Byte hours) {
        this.hours = hours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column course.credit
     *
     * @return the value of course.credit
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public Byte getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column course.credit
     *
     * @param credit the value for course.credit
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setCredit(Byte credit) {
        this.credit = credit;
    }
}