package com.oa.entity;

import java.util.Date;

public class Leader {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.id
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.name
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.password
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.sex
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.ManagerDepartment
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    private String managerdepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.email
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.info
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.Tel
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.WorkState
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    private String workstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.Register
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    private String register;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.EntryTime
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    private Date entrytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.NativePlace
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    private String nativeplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.age
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    private String age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.id
     *
     * @return the value of leaders.id
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.id
     *
     * @param id the value for leaders.id
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.name
     *
     * @return the value of leaders.name
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.name
     *
     * @param name the value for leaders.name
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.password
     *
     * @return the value of leaders.password
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.password
     *
     * @param password the value for leaders.password
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.sex
     *
     * @return the value of leaders.sex
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.sex
     *
     * @param sex the value for leaders.sex
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.ManagerDepartment
     *
     * @return the value of leaders.ManagerDepartment
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public String getManagerdepartment() {
        return managerdepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.ManagerDepartment
     *
     * @param managerdepartment the value for leaders.ManagerDepartment
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public void setManagerdepartment(String managerdepartment) {
        this.managerdepartment = managerdepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.email
     *
     * @return the value of leaders.email
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.email
     *
     * @param email the value for leaders.email
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.info
     *
     * @return the value of leaders.info
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.info
     *
     * @param info the value for leaders.info
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public void setInfo(String info) {
        this.info = info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.Tel
     *
     * @return the value of leaders.Tel
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.Tel
     *
     * @param tel the value for leaders.Tel
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.WorkState
     *
     * @return the value of leaders.WorkState
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public String getWorkstate() {
        return workstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.WorkState
     *
     * @param workstate the value for leaders.WorkState
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public void setWorkstate(String workstate) {
        this.workstate = workstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.Register
     *
     * @return the value of leaders.Register
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public String getRegister() {
        return register;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.Register
     *
     * @param register the value for leaders.Register
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public void setRegister(String register) {
        this.register = register;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.EntryTime
     *
     * @return the value of leaders.EntryTime
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public Date getEntrytime() {
        return entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.EntryTime
     *
     * @param entrytime the value for leaders.EntryTime
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public void setEntrytime(Date entrytime) {
        this.entrytime = entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.NativePlace
     *
     * @return the value of leaders.NativePlace
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public String getNativeplace() {
        return nativeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.NativePlace
     *
     * @param nativeplace the value for leaders.NativePlace
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public void setNativeplace(String nativeplace) {
        this.nativeplace = nativeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.age
     *
     * @return the value of leaders.age
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.age
     *
     * @param age the value for leaders.age
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public void setAge(String age) {
        this.age = age;
    }
}