package com.oa.entity;

import java.util.Date;

public class Leader {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.leaders_id
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private Integer leadersId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.leaderName
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String leadername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.leaderPassword
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String leaderpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.sex
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.ManagerDepartment
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String managerdepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.email
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.leaderInfo
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String leaderinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.Tel
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.WorkState
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String workstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.Register
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String register;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.EntryTime
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private Date entrytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.NativePlace
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String nativeplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leaders.age
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.leaders_id
     *
     * @return the value of leaders.leaders_id
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public Integer getLeadersId() {
        return leadersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.leaders_id
     *
     * @param leadersId the value for leaders.leaders_id
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setLeadersId(Integer leadersId) {
        this.leadersId = leadersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.leaderName
     *
     * @return the value of leaders.leaderName
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getLeadername() {
        return leadername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.leaderName
     *
     * @param leadername the value for leaders.leaderName
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setLeadername(String leadername) {
        this.leadername = leadername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.leaderPassword
     *
     * @return the value of leaders.leaderPassword
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getLeaderpassword() {
        return leaderpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.leaderPassword
     *
     * @param leaderpassword the value for leaders.leaderPassword
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setLeaderpassword(String leaderpassword) {
        this.leaderpassword = leaderpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.sex
     *
     * @return the value of leaders.sex
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.sex
     *
     * @param sex the value for leaders.sex
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.ManagerDepartment
     *
     * @return the value of leaders.ManagerDepartment
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getManagerdepartment() {
        return managerdepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.ManagerDepartment
     *
     * @param managerdepartment the value for leaders.ManagerDepartment
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setManagerdepartment(String managerdepartment) {
        this.managerdepartment = managerdepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.email
     *
     * @return the value of leaders.email
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.email
     *
     * @param email the value for leaders.email
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.leaderInfo
     *
     * @return the value of leaders.leaderInfo
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getLeaderinfo() {
        return leaderinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.leaderInfo
     *
     * @param leaderinfo the value for leaders.leaderInfo
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setLeaderinfo(String leaderinfo) {
        this.leaderinfo = leaderinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.Tel
     *
     * @return the value of leaders.Tel
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.Tel
     *
     * @param tel the value for leaders.Tel
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.WorkState
     *
     * @return the value of leaders.WorkState
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getWorkstate() {
        return workstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.WorkState
     *
     * @param workstate the value for leaders.WorkState
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setWorkstate(String workstate) {
        this.workstate = workstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.Register
     *
     * @return the value of leaders.Register
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getRegister() {
        return register;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.Register
     *
     * @param register the value for leaders.Register
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setRegister(String register) {
        this.register = register;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.EntryTime
     *
     * @return the value of leaders.EntryTime
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public Date getEntrytime() {
        return entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.EntryTime
     *
     * @param entrytime the value for leaders.EntryTime
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setEntrytime(Date entrytime) {
        this.entrytime = entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.NativePlace
     *
     * @return the value of leaders.NativePlace
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getNativeplace() {
        return nativeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.NativePlace
     *
     * @param nativeplace the value for leaders.NativePlace
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setNativeplace(String nativeplace) {
        this.nativeplace = nativeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leaders.age
     *
     * @return the value of leaders.age
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leaders.age
     *
     * @param age the value for leaders.age
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setAge(String age) {
        this.age = age;
    }
}