package com.oa.entity;

import java.util.Date;

public class Leave {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.LeaveNo
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private Byte leaveno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.ApplicantName
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String applicantname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.ApplicantStartTime
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private Byte applicantstarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.ApplicantEndTime
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private Date applicantendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.ApproveTime
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private Date approvetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.ApproverName
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String approvername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.LeaveReason
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String leavereason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.ApplicantDepartment
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String applicantdepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.ApplicantJob
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String applicantjob;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.ApplicationStatus
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String applicationstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.ApproverDepartment
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String approverdepartment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.LeaveNo
     *
     * @return the value of leave.LeaveNo
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public Byte getLeaveno() {
        return leaveno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.LeaveNo
     *
     * @param leaveno the value for leave.LeaveNo
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setLeaveno(Byte leaveno) {
        this.leaveno = leaveno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.ApplicantName
     *
     * @return the value of leave.ApplicantName
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getApplicantname() {
        return applicantname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.ApplicantName
     *
     * @param applicantname the value for leave.ApplicantName
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setApplicantname(String applicantname) {
        this.applicantname = applicantname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.ApplicantStartTime
     *
     * @return the value of leave.ApplicantStartTime
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public Byte getApplicantstarttime() {
        return applicantstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.ApplicantStartTime
     *
     * @param applicantstarttime the value for leave.ApplicantStartTime
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setApplicantstarttime(Byte applicantstarttime) {
        this.applicantstarttime = applicantstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.ApplicantEndTime
     *
     * @return the value of leave.ApplicantEndTime
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public Date getApplicantendtime() {
        return applicantendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.ApplicantEndTime
     *
     * @param applicantendtime the value for leave.ApplicantEndTime
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setApplicantendtime(Date applicantendtime) {
        this.applicantendtime = applicantendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.ApproveTime
     *
     * @return the value of leave.ApproveTime
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public Date getApprovetime() {
        return approvetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.ApproveTime
     *
     * @param approvetime the value for leave.ApproveTime
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setApprovetime(Date approvetime) {
        this.approvetime = approvetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.ApproverName
     *
     * @return the value of leave.ApproverName
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getApprovername() {
        return approvername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.ApproverName
     *
     * @param approvername the value for leave.ApproverName
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setApprovername(String approvername) {
        this.approvername = approvername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.LeaveReason
     *
     * @return the value of leave.LeaveReason
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getLeavereason() {
        return leavereason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.LeaveReason
     *
     * @param leavereason the value for leave.LeaveReason
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setLeavereason(String leavereason) {
        this.leavereason = leavereason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.ApplicantDepartment
     *
     * @return the value of leave.ApplicantDepartment
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getApplicantdepartment() {
        return applicantdepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.ApplicantDepartment
     *
     * @param applicantdepartment the value for leave.ApplicantDepartment
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setApplicantdepartment(String applicantdepartment) {
        this.applicantdepartment = applicantdepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.ApplicantJob
     *
     * @return the value of leave.ApplicantJob
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getApplicantjob() {
        return applicantjob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.ApplicantJob
     *
     * @param applicantjob the value for leave.ApplicantJob
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setApplicantjob(String applicantjob) {
        this.applicantjob = applicantjob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.ApplicationStatus
     *
     * @return the value of leave.ApplicationStatus
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getApplicationstatus() {
        return applicationstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.ApplicationStatus
     *
     * @param applicationstatus the value for leave.ApplicationStatus
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setApplicationstatus(String applicationstatus) {
        this.applicationstatus = applicationstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.ApproverDepartment
     *
     * @return the value of leave.ApproverDepartment
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getApproverdepartment() {
        return approverdepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.ApproverDepartment
     *
     * @param approverdepartment the value for leave.ApproverDepartment
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setApproverdepartment(String approverdepartment) {
        this.approverdepartment = approverdepartment;
    }
}