package com.oa.entity;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.MessageNo
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private Byte messageno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.MessageContent
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String messagecontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.MessageSender
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String messagesender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.MessageTaker
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String messagetaker;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.MessageType
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String messagetype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.MessageNo
     *
     * @return the value of message.MessageNo
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public Byte getMessageno() {
        return messageno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.MessageNo
     *
     * @param messageno the value for message.MessageNo
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setMessageno(Byte messageno) {
        this.messageno = messageno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.MessageContent
     *
     * @return the value of message.MessageContent
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getMessagecontent() {
        return messagecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.MessageContent
     *
     * @param messagecontent the value for message.MessageContent
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setMessagecontent(String messagecontent) {
        this.messagecontent = messagecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.MessageSender
     *
     * @return the value of message.MessageSender
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getMessagesender() {
        return messagesender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.MessageSender
     *
     * @param messagesender the value for message.MessageSender
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setMessagesender(String messagesender) {
        this.messagesender = messagesender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.MessageTaker
     *
     * @return the value of message.MessageTaker
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getMessagetaker() {
        return messagetaker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.MessageTaker
     *
     * @param messagetaker the value for message.MessageTaker
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setMessagetaker(String messagetaker) {
        this.messagetaker = messagetaker;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.MessageType
     *
     * @return the value of message.MessageType
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getMessagetype() {
        return messagetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.MessageType
     *
     * @param messagetype the value for message.MessageType
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setMessagetype(String messagetype) {
        this.messagetype = messagetype;
    }
}