package com.oa.entity;

import java.util.Date;

public class Reimbursement {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimbursement.ReimbursementNo
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private Byte reimbursementno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimbursement.ApplicantName
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String applicantname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimbursement.ApplicantDepartment
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String applicantdepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimbursement.ApplicantJob
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String applicantjob;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimbursement.ReimbursementType
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String reimbursementtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimbursement.ReimbursementMoney
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private Integer reimbursementmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimbursement.ApproveTime
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private Date approvetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimbursement.ApproveName
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String approvename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimbursement.ApproverDepartment
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String approverdepartment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimbursement.ReimbursementStatus
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String reimbursementstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimbursement.ReimbursementNo
     *
     * @return the value of reimbursement.ReimbursementNo
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public Byte getReimbursementno() {
        return reimbursementno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimbursement.ReimbursementNo
     *
     * @param reimbursementno the value for reimbursement.ReimbursementNo
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setReimbursementno(Byte reimbursementno) {
        this.reimbursementno = reimbursementno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimbursement.ApplicantName
     *
     * @return the value of reimbursement.ApplicantName
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getApplicantname() {
        return applicantname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimbursement.ApplicantName
     *
     * @param applicantname the value for reimbursement.ApplicantName
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setApplicantname(String applicantname) {
        this.applicantname = applicantname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimbursement.ApplicantDepartment
     *
     * @return the value of reimbursement.ApplicantDepartment
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getApplicantdepartment() {
        return applicantdepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimbursement.ApplicantDepartment
     *
     * @param applicantdepartment the value for reimbursement.ApplicantDepartment
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setApplicantdepartment(String applicantdepartment) {
        this.applicantdepartment = applicantdepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimbursement.ApplicantJob
     *
     * @return the value of reimbursement.ApplicantJob
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getApplicantjob() {
        return applicantjob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimbursement.ApplicantJob
     *
     * @param applicantjob the value for reimbursement.ApplicantJob
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setApplicantjob(String applicantjob) {
        this.applicantjob = applicantjob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimbursement.ReimbursementType
     *
     * @return the value of reimbursement.ReimbursementType
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getReimbursementtype() {
        return reimbursementtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimbursement.ReimbursementType
     *
     * @param reimbursementtype the value for reimbursement.ReimbursementType
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setReimbursementtype(String reimbursementtype) {
        this.reimbursementtype = reimbursementtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimbursement.ReimbursementMoney
     *
     * @return the value of reimbursement.ReimbursementMoney
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public Integer getReimbursementmoney() {
        return reimbursementmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimbursement.ReimbursementMoney
     *
     * @param reimbursementmoney the value for reimbursement.ReimbursementMoney
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setReimbursementmoney(Integer reimbursementmoney) {
        this.reimbursementmoney = reimbursementmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimbursement.ApproveTime
     *
     * @return the value of reimbursement.ApproveTime
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public Date getApprovetime() {
        return approvetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimbursement.ApproveTime
     *
     * @param approvetime the value for reimbursement.ApproveTime
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setApprovetime(Date approvetime) {
        this.approvetime = approvetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimbursement.ApproveName
     *
     * @return the value of reimbursement.ApproveName
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getApprovename() {
        return approvename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimbursement.ApproveName
     *
     * @param approvename the value for reimbursement.ApproveName
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setApprovename(String approvename) {
        this.approvename = approvename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimbursement.ApproverDepartment
     *
     * @return the value of reimbursement.ApproverDepartment
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getApproverdepartment() {
        return approverdepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimbursement.ApproverDepartment
     *
     * @param approverdepartment the value for reimbursement.ApproverDepartment
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setApproverdepartment(String approverdepartment) {
        this.approverdepartment = approverdepartment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimbursement.ReimbursementStatus
     *
     * @return the value of reimbursement.ReimbursementStatus
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getReimbursementstatus() {
        return reimbursementstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimbursement.ReimbursementStatus
     *
     * @param reimbursementstatus the value for reimbursement.ReimbursementStatus
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setReimbursementstatus(String reimbursementstatus) {
        this.reimbursementstatus = reimbursementstatus;
    }
}