package com.oa.entity;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

public class Reimbursement {
    private final static SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd HH:mm:00");
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimbursement.id
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    private Byte id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimbursement.applicantId
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    private Integer applicantid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimbursement.applyTime
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    private Date applytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimbursement.type
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimbursement.money
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    private Integer money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimbursement.approverId
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    private Integer approverid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimbursement.approveTime
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    private Date approvetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reimbursement.ReimbursementStatus
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    private String reimbursementstatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimbursement.id
     *
     * @return the value of reimbursement.id
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    public Byte getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimbursement.id
     *
     * @param id the value for reimbursement.id
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    public void setId(Byte id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimbursement.applicantId
     *
     * @return the value of reimbursement.applicantId
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    public Integer getApplicantid() {
        return applicantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimbursement.applicantId
     *
     * @param applicantid the value for reimbursement.applicantId
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    public void setApplicantid(Integer applicantid) {
        this.applicantid = applicantid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimbursement.applyTime
     *
     * @return the value of reimbursement.applyTime
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    public Date getApplytime() {
        return applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimbursement.applyTime
     *
     * @param applytime the value for reimbursement.applyTime
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    public void setApplytime(Date applytime) {
        this.applytime = applytime;
    }

    public void setApplytime(String applytime) throws ParseException{
        this.applytime = format.parse(applytime);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimbursement.type
     *
     * @return the value of reimbursement.type
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimbursement.type
     *
     * @param type the value for reimbursement.type
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimbursement.money
     *
     * @return the value of reimbursement.money
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    public Integer getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimbursement.money
     *
     * @param money the value for reimbursement.money
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    public void setMoney(Integer money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimbursement.approverId
     *
     * @return the value of reimbursement.approverId
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    public Integer getApproverid() {
        return approverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimbursement.approverId
     *
     * @param approverid the value for reimbursement.approverId
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    public void setApproverid(Integer approverid) {
        this.approverid = approverid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimbursement.approveTime
     *
     * @return the value of reimbursement.approveTime
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    public Date getApprovetime() {
        return approvetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimbursement.approveTime
     *
     * @param approvetime the value for reimbursement.approveTime
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    public void setApprovetime(Date approvetime) {
        this.approvetime = approvetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reimbursement.ReimbursementStatus
     *
     * @return the value of reimbursement.ReimbursementStatus
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    public String getReimbursementstatus() {
        return reimbursementstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reimbursement.ReimbursementStatus
     *
     * @param reimbursementstatus the value for reimbursement.ReimbursementStatus
     *
     * @mbg.generated Wed Jun 07 09:28:24 CST 2017
     */
    public void setReimbursementstatus(String reimbursementstatus) {
        this.reimbursementstatus = reimbursementstatus;
    }
}