package com.oa.entity;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.studentId
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private Integer studentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.studentName
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String studentname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.studentPassword
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String studentpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.sex
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.s_Class
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String sClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.club
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String club;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.email
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.Tel
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.NativePlace
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String nativeplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.age
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.studentId
     *
     * @return the value of students.studentId
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public Integer getStudentid() {
        return studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.studentId
     *
     * @param studentid the value for students.studentId
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setStudentid(Integer studentid) {
        this.studentid = studentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.studentName
     *
     * @return the value of students.studentName
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getStudentname() {
        return studentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.studentName
     *
     * @param studentname the value for students.studentName
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setStudentname(String studentname) {
        this.studentname = studentname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.studentPassword
     *
     * @return the value of students.studentPassword
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getStudentpassword() {
        return studentpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.studentPassword
     *
     * @param studentpassword the value for students.studentPassword
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setStudentpassword(String studentpassword) {
        this.studentpassword = studentpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.sex
     *
     * @return the value of students.sex
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.sex
     *
     * @param sex the value for students.sex
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.s_Class
     *
     * @return the value of students.s_Class
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getsClass() {
        return sClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.s_Class
     *
     * @param sClass the value for students.s_Class
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setsClass(String sClass) {
        this.sClass = sClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.club
     *
     * @return the value of students.club
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getClub() {
        return club;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.club
     *
     * @param club the value for students.club
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setClub(String club) {
        this.club = club;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.email
     *
     * @return the value of students.email
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.email
     *
     * @param email the value for students.email
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.Tel
     *
     * @return the value of students.Tel
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.Tel
     *
     * @param tel the value for students.Tel
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.NativePlace
     *
     * @return the value of students.NativePlace
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getNativeplace() {
        return nativeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.NativePlace
     *
     * @param nativeplace the value for students.NativePlace
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setNativeplace(String nativeplace) {
        this.nativeplace = nativeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.age
     *
     * @return the value of students.age
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.age
     *
     * @param age the value for students.age
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setAge(String age) {
        this.age = age;
    }
}