package com.oa.entity;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.id
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.name
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.password
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.sex
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.s_Class
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    private String sClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.club
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    private String club;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.email
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.Tel
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.NativePlace
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    private String nativeplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column students.age
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    private String age;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.id
     *
     * @return the value of students.id
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.id
     *
     * @param id the value for students.id
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.name
     *
     * @return the value of students.name
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.name
     *
     * @param name the value for students.name
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.password
     *
     * @return the value of students.password
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.password
     *
     * @param password the value for students.password
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.sex
     *
     * @return the value of students.sex
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.sex
     *
     * @param sex the value for students.sex
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.s_Class
     *
     * @return the value of students.s_Class
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public String getsClass() {
        return sClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.s_Class
     *
     * @param sClass the value for students.s_Class
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public void setsClass(String sClass) {
        this.sClass = sClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.club
     *
     * @return the value of students.club
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public String getClub() {
        return club;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.club
     *
     * @param club the value for students.club
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public void setClub(String club) {
        this.club = club;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.email
     *
     * @return the value of students.email
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.email
     *
     * @param email the value for students.email
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.Tel
     *
     * @return the value of students.Tel
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.Tel
     *
     * @param tel the value for students.Tel
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.NativePlace
     *
     * @return the value of students.NativePlace
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public String getNativeplace() {
        return nativeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.NativePlace
     *
     * @param nativeplace the value for students.NativePlace
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public void setNativeplace(String nativeplace) {
        this.nativeplace = nativeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column students.age
     *
     * @return the value of students.age
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column students.age
     *
     * @param age the value for students.age
     *
     * @mbg.generated Wed Jun 07 08:17:00 CST 2017
     */
    public void setAge(String age) {
        this.age = age;
    }
}