package com.oa.entity;

import java.util.Date;

public class Teacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.teacherId
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private Integer teacherid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.teacherName
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String teachername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.teacherPassword
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String teacherpassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.sex
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.ManagerClass
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String managerclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.teacherInfo
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String teacherinfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.email
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.WorkState
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String workstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.Tel
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.Department
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.age
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.NativePlace
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String nativeplace;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.EntryTime
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private Date entrytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teachers.Register
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    private String register;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.teacherId
     *
     * @return the value of teachers.teacherId
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public Integer getTeacherid() {
        return teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.teacherId
     *
     * @param teacherid the value for teachers.teacherId
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setTeacherid(Integer teacherid) {
        this.teacherid = teacherid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.teacherName
     *
     * @return the value of teachers.teacherName
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getTeachername() {
        return teachername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.teacherName
     *
     * @param teachername the value for teachers.teacherName
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setTeachername(String teachername) {
        this.teachername = teachername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.teacherPassword
     *
     * @return the value of teachers.teacherPassword
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getTeacherpassword() {
        return teacherpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.teacherPassword
     *
     * @param teacherpassword the value for teachers.teacherPassword
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setTeacherpassword(String teacherpassword) {
        this.teacherpassword = teacherpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.sex
     *
     * @return the value of teachers.sex
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.sex
     *
     * @param sex the value for teachers.sex
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.ManagerClass
     *
     * @return the value of teachers.ManagerClass
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getManagerclass() {
        return managerclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.ManagerClass
     *
     * @param managerclass the value for teachers.ManagerClass
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setManagerclass(String managerclass) {
        this.managerclass = managerclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.teacherInfo
     *
     * @return the value of teachers.teacherInfo
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getTeacherinfo() {
        return teacherinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.teacherInfo
     *
     * @param teacherinfo the value for teachers.teacherInfo
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setTeacherinfo(String teacherinfo) {
        this.teacherinfo = teacherinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.email
     *
     * @return the value of teachers.email
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.email
     *
     * @param email the value for teachers.email
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.WorkState
     *
     * @return the value of teachers.WorkState
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getWorkstate() {
        return workstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.WorkState
     *
     * @param workstate the value for teachers.WorkState
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setWorkstate(String workstate) {
        this.workstate = workstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.Tel
     *
     * @return the value of teachers.Tel
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.Tel
     *
     * @param tel the value for teachers.Tel
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.Department
     *
     * @return the value of teachers.Department
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.Department
     *
     * @param department the value for teachers.Department
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.age
     *
     * @return the value of teachers.age
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.age
     *
     * @param age the value for teachers.age
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setAge(String age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.NativePlace
     *
     * @return the value of teachers.NativePlace
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getNativeplace() {
        return nativeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.NativePlace
     *
     * @param nativeplace the value for teachers.NativePlace
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setNativeplace(String nativeplace) {
        this.nativeplace = nativeplace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.EntryTime
     *
     * @return the value of teachers.EntryTime
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public Date getEntrytime() {
        return entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.EntryTime
     *
     * @param entrytime the value for teachers.EntryTime
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setEntrytime(Date entrytime) {
        this.entrytime = entrytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teachers.Register
     *
     * @return the value of teachers.Register
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public String getRegister() {
        return register;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teachers.Register
     *
     * @param register the value for teachers.Register
     *
     * @mbg.generated Mon Jun 05 13:40:35 CST 2017
     */
    public void setRegister(String register) {
        this.register = register;
    }
}